MYSHOP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path
from shop_app.views import UserRegisterView, UserLoginView, SellerLoginView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("shop_app.urls")),
    


    path("accounts/user-login/", UserLoginView.as_view(), name="user-login"),
    path("accounts/user-logout/", views.LogoutView.as_view(), name="user-logout"),
    path('user-registration/', UserRegisterView.as_view(), name='user-registration'),


    # path('api/', include('cart.urls')),

   
    path("accounts/seller-login/", SellerLoginView.as_view(), name="seller-login"),
    path("accounts/seller-logout/", views.LogoutView.as_view(), name="seller-logout"),
    path('seller/', include('seller_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import *

# urlpatterns = [
#     path('cart', CartListView.as_view( )),
# ]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
# Create your models here.
from shop_app.models import Item
from django.db.models.signals import post_save, pre_save
from django.db.models import Sum

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.BooleanField(default=False) 
    total_price = models.FloatField(default=0)

    def __str__(self):
        return str(self.user.username) + " "+ str(self.total_price)


class CartItems(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    cart_total_price = models.FloatField(default=0)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.user.username) + " "+ str(self.item.name)
    
from decimal import Decimal


@receiver(pre_save, sender=CartItems)
def correct_price(sender, **kwargs):
    cart_items = kwargs['instance']
    price_of_item = Item.objects.get(id=cart_items.item.id)
    
    cart_items.price = price_of_item.price
    cart_items.cart_total_price = cart_items.quantity * float(price_of_item.price)
    total_cart_items = CartItems.objects.filter(user=cart_items.user)

    cart = Cart.objects.get(id=cart_items.cart.id)
    
    cart.total_price = sum(item.cart_total_price for item in total_cart_items) + float(cart_items.cart_total_price)
    cart.save()

shop_app/models.py
from django.db import models

from decimal import Decimal, ROUND_DOWN


# Create your models here.



class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # no table for this model



class Contact(TimeStampModel):
    message = models.TextField()
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)

    def __str__(self):
        return self.name



class Newsletter(TimeStampModel):
    email = models.EmailField()


    def __str__(self):
        return f"{self.email}"
    

class Customer(TimeStampModel):
    fname = models.CharField(max_length=25)
    mname = models.CharField(max_length=25, blank=True)
    lname = models.CharField(max_length=25)
    contact = models.BigIntegerField(blank=True, null=True)
    location = models.CharField(max_length=25)


class Category(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class TrendingItemCategory(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class TargetCustomer(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Brand(TimeStampModel):
    name = models.CharField(max_length=50)

    def __str__(self):
            return self.name

class Item(TimeStampModel):
    STATUS_CHOICES = [
        ("in stock", "In Stock"),
        ("out of stock", "Out of Stock"),
    ]
    name = models.CharField(max_length=200)
    detail = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discont_percent = models.DecimalField(max_digits=4, decimal_places=2)
        
    def discounted_price(self):
        discount = self.price * (self.discont_percent / 100)
        discounted_price = self.price - discount
        return discounted_price.quantize(Decimal('0.00'), rounding=ROUND_DOWN)

    featured_image = models.ImageField(upload_to="item_images/%Y/%m/%d", blank=False)
    other_image = models.ImageField(upload_to="item_images/%Y/%m/%d", blank=False)
    target_customer = models.ManyToManyField(TargetCustomer)
    seller = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    listed_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="in stock")
    views_count = models.PositiveBigIntegerField(default=0)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    trending_items_category = models.ForeignKey(TrendingItemCategory, default=1 ,on_delete=models.CASCADE)
   

    def __str__(self):
        return self.name
    

class Comment(TimeStampModel):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    comment = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return f"{self.email} | {self.comment[:70]}"

cart/views.py
from django.shortcuts import render

templates/eshop/about.html
{% extends 'eshop/base.html' %}
{% load static %}
{% block content %}





</header>
<!--/ End Header -->

<!-- Breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="bread-inner">
					<ul class="bread-list">
						<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
						<li class="active"><a href="blog-single.html">About</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Breadcrumbs -->

<!-- Start Blog Single -->
<section class="blog-single section">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-12">
				<div class="blog-single-main">
					<div class="row">
						<div class="col-12">
							<div class="image">
								<img src="https://via.placeholder.com/950x460" alt="#">
							</div>
							<div class="blog-detail">
								<h2 class="blog-title">About Eshop</h2>
								
								<div class="content">
									<p>What a crazy time. I have five children in colleghigh school graduates.jpge or
										pursing post graduate studies Each of my children attends college far from home,
										the closest of which is more than 800 miles away. While I miss being with my
										older children, I know that a college experience can be the source of great
										growth and experience can be the source of source of great growth and can
										provide them with even greater in future.</p>
									<blockquote> <i class="fa fa-quote-left"></i> Do what you love to do and give it
										your very best. Whether it's business or baseball, or the theater, or any field.
										If you don't love what you're doing and you can't give it your best, get out of
										it. Life is too short. You'll be an old man before you know it. risus. Ut
										tincidunt, erat eget feugiat eleifend, eros magna dapibus diam.</blockquote>
									<p>What a crazy time. I have five children in colleghigh school graduates.jpge or
										pursing post graduate studies Each of my children attends college far from home,
										the closest of which is more than 800 miles away. While I miss being with my
										older children, I know that a college experience can be the source of great
										growth and experience can be the source of source of great growth and can
										provide them with even greater in future.</p>
									<p>What a crazy time. I have five children in colleghigh school graduates.jpge or
										pursing post graduate studies Each of my children attends college far from home,
										the closest of which is more than 800 miles away. While I miss being with my
										older children, I know that a college experience can be the source of great
										growth and experience can be the source of source of great growth and can
										provide them with even greater in future.</p>
								</div>
							</div>
							
						</div>
						
						
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-12">
				<div class="main-sidebar">
					
					<!-- Single Widget -->
					<div class="single-widget category">
						<h3 class="title">Blog Categories</h3>
						<ul class="categor-list">
							<li><a href="#">Men's Apparel</a></li>
							<li><a href="#">Women's Apparel</a></li>
							<li><a href="#">Bags Collection</a></li>
							<li><a href="#">Accessories</a></li>
							<li><a href="#">Sun Glasses</a></li>
						</ul>
					</div>
					
					<!-- Single Widget -->
					<div class="single-widget side-tags">
						<h3 class="title">Tags</h3>
						<ul class="tag">
							<li><a href="#">business</a></li>
							<li><a href="#">wordpress</a></li>
							<li><a href="#">html</a></li>
							<li><a href="#">multipurpose</a></li>
						</ul>
					</div>
					<!--/ End Single Widget -->
					<!-- Single Widget -->
					<div class="single-widget newsletter">
						<h3 class="title">Newslatter</h3>
						<div class="letter-inner">
							<h4>Subscribe & get news <br> latest updates.</h4>
							<div class="form-inner">
								<input type="email" placeholder="Enter your email">
								<a href="#">Submit</a>
							</div>
						</div>
					</div>
					<!--/ End Single Widget -->
				</div>
			</div>
		</div>
	</div>
</section>
<!--/ End Blog Single -->

{% include 'eshop/shop_services_area.html' %}


{% endblock content %}

templates/eshop/cart.html
{% extends 'eshop/base.html' %}
{% load static %}
{% block content %}

</header>
<!--/ End Header -->

<!-- Breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="bread-inner">
					<ul class="bread-list">
						<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
						<li class="active"><a href="blog-single.html">Cart</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Breadcrumbs -->

<!-- Shopping Cart -->
<div class="shopping-cart section">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Shopping Summery -->
				<table class="table shopping-summery">
					<thead>
						<tr class="main-hading">
							<th>PRODUCT</th>
							<th>NAME</th>
							<th class="text-center">UNIT PRICE</th>
							<th class="text-center">QUANTITY</th>
							<th class="text-center">TOTAL</th>
							<th class="text-center"><i class="ti-trash remove-icon"></i></th>
						</tr>
					</thead>
					<tbody>
						{% for i in cart_items %}
						<tr>
							<td class="image" data-title="No"><img src="https://via.placeholder.com/100x100" alt="#">
							</td>
							<td class="product-des" data-title="Description">
								<p class="product-name"><a href="#">{{ i.item.name }}</a></p>
								<p class="product-des">Maboriosam in a tonto nesciung eget distingy magndapibus.</p>
							</td>
							<td class="price" data-title="Price"><span>Rs. {{ i.price }}</span></td>
							<td class="qty" data-title="Qty">
								<!-- Input Order -->
								<div class="input-group">

									<form action="{% url 'update-cart-item' i.pk %}" method="post">
										{% csrf_token %}
										<div class="button minus">
											<button type="button" class="btn btn-primary btn-number" disabled="disabled"
												data-type="minus" data-field="quantity{{ i.pk }}">
												<i class="ti-minus"></i>
											</button>
										</div>
										<input type="number" id="quantity{{ i.pk }}" name="quantity{{ i.pk }}"
											class="input-number" data-min="1" data-max="100" value="{{ i.quantity }}">

										<div class="button plus">
											<button type="button" class="btn btn-primary btn-number" data-type="plus"
												data-field="quantity{{ i.pk }}">
												<i class="ti-plus"></i>
											</button>
										</div>
									</form>
								</div>
								<!--/ End Input Order -->
							</td>
							<td class="total-amount" data-title="Total"><span>Rs. {{ i.cart_total_price }}</span></td>
							<td class="action" data-title="Remove">
								<a href="{% url 'delete-cart-item' i.pk %}"><i class="ti-trash remove-icon"></i></a>
							</td>
						</tr>
						{% endfor %}


					</tbody>
				</table>
				<!--/ End Shopping Summery -->
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!-- Total Amount -->
				<div class="total-amount">
					<div class="row">
						<div class="col-lg-8 col-md-5 col-12">
							<div class="left">
								<div class="coupon">
									<form action="#" target="_blank">
										<input name="Coupon" placeholder="Enter Your Coupon">
										<button class="btn">Apply</button>
									</form>
								</div>
								<div class="checkbox">
									<label class="checkbox-inline" for="2"><input name="news" id="2" type="checkbox">
										Super shipping (+10$)</label>
								</div>
							</div>
						</div>
						<div class="col-lg-4 col-md-7 col-12">
							<div class="right">
								<ul>
									<li>Cart Subtotal<span>Rs. </span></li>
									<li>Shipping<span>Free</span></li>
									<li class="last">You Pay<span>Rs. </span></li>
								</ul>
								<div class="button5">
									<a href="{% url 'checkout' %}" class="btn">Checkout</a>
									<a href="/" class="btn">Continue shopping</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/ End Total Amount -->
			</div>
		</div>
	</div>
</div>
<!--/ End Shopping Cart -->

{% include 'eshop/shop_services_area.html' %}
{% include 'eshop/newsletter.html' %}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="ti-close"
						aria-hidden="true"></span></button>
			</div>
			<div class="modal-body">
				<div class="row no-gutters">
					<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
						<!-- Product Slider -->
						<div class="product-gallery">
							<div class="quickview-slider-active">
								<div class="single-slider">
									<img src="images/modal1.jpg" alt="#">
								</div>
								<div class="single-slider">
									<img src="images/modal2.jpg" alt="#">
								</div>
								<div class="single-slider">
									<img src="images/modal3.jpg" alt="#">
								</div>
								<div class="single-slider">
									<img src="images/modal4.jpg" alt="#">
								</div>
							</div>
						</div>
						<!-- End Product slider -->
					</div>
					<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
						<div class="quickview-content">
							<h2>Flared Shift Dress</h2>
							<div class="quickview-ratting-review">
								<div class="quickview-ratting-wrap">
									<div class="quickview-ratting">
										<i class="yellow fa fa-star"></i>
										<i class="yellow fa fa-star"></i>
										<i class="yellow fa fa-star"></i>
										<i class="yellow fa fa-star"></i>
										<i class="fa fa-star"></i>
									</div>
									<a href="#"> (1 customer review)</a>
								</div>
								<div class="quickview-stock">
									<span><i class="fa fa-check-circle-o"></i> in stock</span>
								</div>
							</div>
							<h3>$29.00</h3>
							<div class="quickview-peragraph">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia iste laborum ad
									impedit pariatur esse optio tempora sint ullam autem deleniti nam in quos qui nemo
									ipsum numquam.</p>
							</div>
							<div class="size">
								<div class="row">
									<div class="col-lg-6 col-12">
										<h5 class="title">Size</h5>
										<select>
											<option selected="selected">s</option>
											<option>m</option>
											<option>l</option>
											<option>xl</option>
										</select>
									</div>
									<div class="col-lg-6 col-12">
										<h5 class="title">Color</h5>
										<select>
											<option selected="selected">orange</option>
											<option>purple</option>
											<option>black</option>
											<option>pink</option>
										</select>
									</div>
								</div>
							</div>
							<div class="quantity">
								<!-- Input Order -->
								<div class="input-group">
									<div class="button minus">
										<button type="button" class="btn btn-primary btn-number" disabled="disabled"
											data-type="minus" data-field="quant[1]">
											<i class="ti-minus"></i>
										</button>
									</div>
									<input type="text" name="quant[1]" class="input-number" data-min="1" data-max="1000"
										value="1">
									<div class="button plus">
										<button type="button" class="btn btn-primary btn-number" data-type="plus"
											data-field="quant[1]">
											<i class="ti-plus"></i>
										</button>
									</div>
								</div>
								<!--/ End Input Order -->
							</div>
							<div class="add-to-cart">
								<a href="#" class="btn">Add to cart</a>
								<a href="#" class="btn min"><i class="ti-heart"></i></a>
								<a href="#" class="btn min"><i class="fa fa-compress"></i></a>
							</div>
							<div class="default-social">
								<h4 class="share-now">Share:</h4>
								<ul>
									<li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a class="youtube" href="#"><i class="fa fa-pinterest-p"></i></a></li>
									<li><a class="dribbble" href="#"><i class="fa fa-google-plus"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Modal end -->

{% endblock content %}

templates/eshop/newsletter.html
{% load static %}

<!-- Start Shop Newsletter  -->
<section class="shop-newsletter section">
	<div class="container">
		<div class="inner-top">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 col-12">
					<!-- Start Newsletter Inner -->
					<div class="inner">
						<h4>Newsletter</h4>
						<p> Subscribe to our newsletter and get <span>10%</span> off your first purchase</p>
						<div id="newsletter_form_message"></div>
						<form action="" id="newsletter_form" method="get" target="_blank" class="newsletter-inner">
							{% csrf_token %}
							<input name="email" placeholder="Your email address" required="" type="email">
							<button class="btn">Subscribe</button>
						</form>
					</div>
					<!-- End Newsletter Inner -->
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End Shop Newsletter -->

templates/eshop/pagination.html
{% load static %}
<div class="pagination-container">
{% if page_obj.has_other_pages %}
  <nav class="blog-pagination justify-content-center d-flex ">
    <ul class="pagination pagination-horizontal ">

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}"
             class="page-link pagination_number"
             aria-label="Previous">
            <i class="ti-angle-left"></i>
          </a>
        </li>
      {% endif %}

      {% for i in page_obj.paginator.page_range %}
        <li class="page-item {% if i == page_obj.number %} active{% endif %}">
          <a href="?page={{i}}" class="page-link pagination_number">{{ i }}</a>
        </li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}"
             class="page-link pagination_number"
             aria-label="Next">
            <i class="ti-angle-right"></i>
          </a>
        </li>
      {% endif %}

    </ul>
  </nav>
</div>
{% endif %}

templates/eshop/product_detail.html
{% extends 'eshop/base.html' %}
{% load static %}
{% block content %}

</header>
<!--/ End Header -->

<!-- Breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="bread-inner">
					<ul class="bread-list">
						<li><a href="/">Home<i class="ti-arrow-right"></i></a></li>
						<li class="active"><a href="blog-single.html">Product Detail</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Breadcrumbs -->

<!-- Start Blog Single -->
<section class="blog-single section">
	<div class="container">
		<div class="blog-detail">
			<h2 class="blog-title">{{ item.name }}</h2>
		</div>
		<div class="row">
			<div class="col-lg-5 col-12">
				<div class="blog-single-main">

					<div class="col-12">
						<div class="image">
							<img src="{{ item.featured_image.url }}" alt="{{ item.name }}">
						</div>

					</div>

				</div>
			</div>
			<div class="col-lg-7 col-12">
				<div class="main-sidebar">
					<form method="POST" action="{% url 'detail' item.id %}">
						{% csrf_token %}
						<div class="blog-detail">
							<h2 class="blog-title">{{item.name}}</h2>
						</div>
						<br>
						<h6><span>{{ item.seller }}</span></h6>
						<br>
						<h6 style="color: orange;">Rs. <span>{{ item.price }}</span></h6>
						<br>
						<br>
						<!-- start qty take it to the center-->
						<h6 class="title">Quantity</h6>


						<!-- Input Order -->
						<div class="input-group">
							<!-- <span><h6 class="title">Qty. </h6></span> -->
							<div class="button minus">
								<button type="button" class="btn btn-primary btn-number" data-type="minus"
									data-field="quantity">
									<i class="ti-minus"></i>
								</button>
							</div>
							<input type="number" id="quantity" name="quantity" class="input-number" data-min="1"
								data-max="100" value="1" style="width: 18%; text-align: center;">
							<div class="button plus">
								<button type="button" class="btn btn-primary btn-number" data-type="plus"
									data-field="quantity">
									<i class="ti-plus"></i>
								</button>
							</div>
						</div>
						<!--/ End Input Order -->
						</td>
						<br>
						<!-- end qty -->
						<!-- start buttons -->
						<div class="d-grid gap-2 d-md-block">
							{% if user.is_authenticated %}

							<a href="{% url 'cart' %}"><button class="btn btn-primary" type="button">Buy
									Now</button></a>
							{% else %}
							<a href="{% url 'user-login' %}"><button class="btn btn-primary" type="button">Buy
									Now</button></a>
							{% endif %}
							{% if user.is_authenticated %}

							<button class="btn btn-primary" type="submit">Add to Cart</button>
							{% else %}
							<a href="{% url 'user-login' %}"><button class="btn btn-primary" type="button">Add to
									Cart</button></a>
							{% endif %}

						</div>
						<!-- end buttons -->
					</form>
				</div>
			</div>
		</div>


		<div class="row">
			<div class="col-lg-8 col-12">

				<div class="blog-single-main">
					<div class="row">
						<div class="col-12">
							{{ item.detail|safe}}

						</div>

					</div>
					<div class="col-12">
						<div class="comments">
							<h3 class="comment-title">Comments (3)</h3>
							<!-- Single Comment -->
							<div class="single-comment">
								<img src="https://via.placeholder.com/80x80" alt="#">
								<div class="content">
									<h4>Alisa harm <span>At 8:59 pm On Feb 28, 2018</span></h4>
									<p>Enthusiastically leverage existing premium quality vectors with
										enterprise-wide innovation collaboration Phosfluorescently leverage others
										enterprisee Phosfluorescently leverage.</p>
									<div class="button">
										<a href="#" class="btn"><i class="fa fa-reply" aria-hidden="true"></i>Reply</a>
									</div>
								</div>
							</div>
							<!-- End Single Comment -->
							<!-- Single Comment -->
							<div class="single-comment left">
								<img src="https://via.placeholder.com/80x80" alt="#">
								<div class="content">
									<h4>john deo <span>Feb 28, 2018 at 8:59 pm</span></h4>
									<p>Enthusiastically leverage existing premium quality vectors with
										enterprise-wide innovation collaboration Phosfluorescently leverage others
										enterprisee Phosfluorescently leverage.</p>
									<div class="button">
										<a href="#" class="btn"><i class="fa fa-reply" aria-hidden="true"></i>Reply</a>
									</div>
								</div>
							</div>
							<!-- End Single Comment -->
							<!-- Single Comment -->
							{% for comment in item.comment_set.all %}
							<div class="single-comment">
								<img src="https://via.placeholder.com/80x80" alt="{{ comment.name }}">
								<div class="content">
									<h4>{{ comment.name }}<span>{{ comment.created_at }}</span></h4>
									<p>{{ comment.comment}}</p>
									<div class="button">
										<a href="#" class="btn"><i class="fa fa-reply" aria-hidden="true"></i>Reply</a>
									</div>
								</div>
							</div>
							{% endfor %}
							<!-- End Single Comment -->
						</div>
					</div>
					<div class="col-12">
						<div class="reply">
							<div class="reply-head">
								<h2 class="reply-title">Leave a Comment</h2>
								<!-- Comment Form -->
								<form class="form" action="{% url 'comment' %}" id="commentForm" method="POST">
									{% csrf_token %}
									<input type="hidden" name="item" value="{{ item.id }}">
									<div class="row">
										<div class="col-lg-6 col-md-6 col-12">
											<div class="form-group">
												<label>Your Name<span>*</span></label>
												<input type="text" name="name" id="name" placeholder=""
													required="required">
												{{ form.name.errors }}

											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-12">
											<div class="form-group">
												<label>Your Email<span>*</span></label>
												<input type="email" name="email" id="email" placeholder=""
													required="required">
												{{ form.email.errors }}

											</div>
										</div>
										<div class="col-12">
											<div class="form-group">
												<label>Your Comment<span>*</span></label>
												<textarea name="comment" id="comment" placeholder=""></textarea>
												{{ form.comment.errors }}
											</div>
										</div>
										<div class="col-12">
											<div class="form-group button">
												<button type="submit" class="btn">Post comment</button>
											</div>
										</div>
									</div>
								</form>
								<!-- End Comment Form -->
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-12">
				<div class="main-sidebar">

					<!-- Single Widget -->
					<div class="single-widget recent-post">
						<h3 class="title">Similar Products</h3>
						<!-- Single Post -->
						{% for item in related_items %}
						<div class="single-post">
							<div class="image">
								<img src="{{ item.featured_image.url }}" alt="{{ item.name }}">
							</div>
							<div class="content">
								<h5><a href="{% url 'detail' item.pk %}">{{ item.name }}</a></h5>
								<p>Rs. {{ item.discounted_price }}</p>
							</div>
						</div>
						{% endfor %}
						<!-- End Single Post -->

					</div>
					<!--/ End Single Widget -->

				</div>
			</div>
		</div>
	</div>
</section>
<!--/ End Blog Single -->

{% endblock content %}

templates/eshop/shop_services_area.html
{% load static %}


<!-- Start Shop Services Area -->
<section class="shop-services section home">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6 col-12">
				<!-- Start Single Service -->
				<div class="single-service">
					<i class="ti-rocket"></i>
					<h4>Free shiping</h4>
					<p>Orders over Rs. 5,000</p>
				</div>
				<!-- End Single Service -->
			</div>
			<div class="col-lg-3 col-md-6 col-12">
				<!-- Start Single Service -->
				<div class="single-service">
					<i class="ti-reload"></i>
					<h4>Free Return</h4>
					<p>Within 7 days returns</p>
				</div>
				<!-- End Single Service -->
			</div>
			<div class="col-lg-3 col-md-6 col-12">
				<!-- Start Single Service -->
				<div class="single-service">
					<i class="ti-lock"></i>
					<h4>Sucure Payment</h4>
					<p>100% secure payment</p>
				</div>
				<!-- End Single Service -->
			</div>
			<div class="col-lg-3 col-md-6 col-12">
				<!-- Start Single Service -->
				<div class="single-service">
					<i class="ti-tag"></i>
					<h4>Best Peice</h4>
					<p>Guaranteed price</p>
				</div>
				<!-- End Single Service -->
			</div>
		</div>
	</div>
</section>
<!-- End Shop Services Area -->