MYSHOP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path
from shop_app.views import UserRegisterView, UserLoginView, SellerLoginView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("shop_app.urls")),
    


    path("accounts/user-login/", UserLoginView.as_view(), name="user-login"),
    path("accounts/user-logout/", views.LogoutView.as_view(), name="user-logout"),
    path('user-registration/', UserRegisterView.as_view(), name='user-registration'),


    # path('api/', include('cart.urls')),

   
    path("accounts/seller-login/", SellerLoginView.as_view(), name="seller-login"),
    path("accounts/seller-logout/", views.LogoutView.as_view(), name="seller-logout"),
    path('seller/', include('seller_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import *

# urlpatterns = [
#     path('cart', CartListView.as_view( )),
# ]

seller_app/urls.py
from django.urls import path

from seller_app import views


app_name = "seller"

urlpatterns = [
    path("", views.ItemListView.as_view(), name="item-list"),
    path("item-detail/<int:pk>/", views.ItemDetailView.as_view(), name="item-detail"),
    path("draft-list/", views.DraftListView.as_view(), name="draft-list"),
    path("draft-detail/<int:pk>/", views.DraftDetailView.as_view(), name="draft-detail"),
    path("draft-publish/<int:pk>/", views.DraftPublishView.as_view(), name="draft-publish"),
    path("item-delete/<int:pk>/", views.ItemDeleteView.as_view(), name="item-delete"),
    path("item-create/", views.ItemCreateView.as_view(), name="item-create"),
    path("item-update/<int:pk>/", views.ItemUpdateView.as_view(), name="item-update"), 
]

templates/seller/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eshop Selller</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap"
          rel="stylesheet">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
  </head>
  <body>
 
 
    <div class="page-header">

      {% if user.is_authenticated %}
        <a href="{% url 'seller-logout' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">logout</span>
        </a>

        <a href="{% url 'seller:item-create' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">add</span>
        </a>

        <a href="{% url 'seller:draft-list' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">draft</span>
        </a>
 
      {% else %}
        <a href="{% url 'seller-login' %}" class="top-menu">
          <span class="material-symbols-outlined lg-icons">login</span>
        </a>
 
      {% endif %}

      <h1>
        <a href="{% url 'seller:item-list' %}">
          <img src="{% static 'images/logo.png' %}"
               alt="Eshop Seller"
               width="90px;">
          Eshop Seller
        </a>
      </h1>
    </div>
    <div class="container content">
      {% block content %}
 
      {% endblock content %}
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

templates/seller/draft_detail.html
{% extends "seller/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      <div class="itme">
        <div class="mt-2">
          <a href="{% url 'seller:draft-publish' item.pk %}" class="btn btn-success">Publish</a>
        </div>
        <h1>
          <a href="#">{{ item.name }}</a>
        </h1>
        <div class="mt-2 my-2">
          <a href="{% url 'seller:item-update' item.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url 'seller:item-delete' item.pk %}" class="btn btn-danger">Delete</a>
        </div>
        <p>Retail Price: Rs. {{ item.price }}</p>
        <p>Discount: {{ item.discont_percent }}%</p>
        <p>Offer price: Rs. {{ item.discounted_price }}</p>
        <div class="date author">@{{ item.seller.username }}</div>
        <p>{{ item.detail|safe }}</p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/seller/draft_list.html
{% extends "seller/base.html" %}

{% block content %}
<h1>Draft Items</h1>
<div class="col-12">
  <div class="section-title">
    <div class="tab-pane fade show active" role="tabpanel">
      <div class="tab-single">
        <div class="row">
          {% for item in items %}
          <div class="col-xl-3 col-lg-4 col-md-4 col-12" style="padding: 2%;">
            <div class="single-product">
              <div class="product-img">
                <a href="{% url 'seller:draft-detail' item.pk %}">
                  <img class="default-img" src="{{ item.featured_image.url }}" alt="item.name" style="height: 180px;"">
                </a>

              </div>
              <div class="product-content">
                <div class="item">
                  <div class="date">{{ item.listed_at }}</div>
                  <div class="date author">@{{ item.seller.username }}</div>

                  <h1>
                    <a href="{% url 'seller:draft-detail' item.pk %}">{{ item.name|truncatechars:30 }}</a>
                  </h1>
                  <p>
                    {{ item.detail|striptags|safe|truncatechars:100 }} <a
                      href="{% url 'seller:draft-detail' item.pk %}">View
                      more</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/seller/item_create.html
{% extends "seller/base.html" %}

{% block content %}
<h1>Create New Item For Sale</h1>

<form action="" method="POST" class="item-form" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock content %}

templates/seller/item_detail.html
{% extends "seller/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      <div class="item">
        <div class="date">{{ item.listed_at }}</div>
        <h1>
          <a href="#">{{ item.title }}</a>
        </h1>
        <div class="mt-2 my-2">
          <a href="{% url 'seller:item-update' item.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url 'seller:item-delete' item.pk %}" class="btn btn-danger">Delete</a>
        </div>
        <div class="date author">@{{ item.seller.username }}</div>
        <p>Retail Price: Rs. {{ item.price }}</p>
        <p>Discount: {{ item.discont_percent }}%</p>
        <p>Offer price: Rs. {{ item.discounted_price }}</p>
        <p>{{ item.detail|safe }}</p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/seller/item_list.html
{% extends "seller/base.html" %}

{% block content %}
<h1>Listed Items</h1>

<div class="col-12">
  <div class="section-title">
    <div class="tab-pane fade show active" role="tabpanel">
      <div class="tab-single">
        <div class="row">
          {% for item in items %}
          <div class="col-xl-3 col-lg-4 col-md-4 col-12" style="padding: 2%;">
            <div class="single-product">
              <div class="product-img">
                <a href="{% url 'seller:item-detail' item.pk %}">
                  <img class="default-img" src="{{ item.featured_image.url }}" alt="{{ item.name }}" style="height: 180px;">
                </a>

              </div>
              <div class="product-content">
                <div class="item">
                  <div class="date">{{ item.listed_at }}</div>
                  <div class="date author">@{{ item.seller.username }}</div>

                  <h1>
                    <a href="{% url 'seller:item-detail' item.pk %}">{{ item.name|truncatechars:30 }}</a>
                  </h1>
                  <p>
                    {{ item.detail|striptags|safe|truncatechars:100 }} <a
                      href="{% url 'seller:item-detail' item.pk %}">View
                      more</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}